### ISSUE TITLE
Error starting server from Python package

### ISSUE THREAD

**Issue by sitabulaixizawaluduo** [Xilinx/inference-server#224]
python: server = amdinfer.Server()
RuntimeError: basic_string::_S_construct null not valid

i installed amdinfer by command pip install amdinfer

**Comment by varunsh-xilinx** [comment]
The Python package on pip is primarily for the client library, which should be usable in any environment. However,  it won't let you start the server unless you're using the development container. In this case, you can look at the [developer quickstart](https://xilinx.github.io/inference-server/main/quickstart_development.html). The error message here should be better though.

Otherwise, you'd need to run a deployment container to launch the server. Take a look at the regular [quickstart](https://xilinx.github.io/inference-server/main/quickstart.html) online to get started.

**Comment by sitabulaixizawaluduo** [comment]
> The Python package on pip is primarily for the client library, which should be usable in any environment. However, it won't let you start the server unless you're using the development container. In this case, you can look at the [developer quickstart](https://xilinx.github.io/inference-server/main/quickstart_development.html). The error message here should be better though.
> 
> Otherwise, you'd need to run a deployment container to launch the server. Take a look at the regular [quickstart](https://xilinx.github.io/inference-server/main/quickstart.html) online to get started.

thanks!!
